# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release -o build DSARatings.App/DSARatings.App.csproj --os win --arch x64 --sc
    - name: Zip
      run: Compress-Archive -Path build/* -Destination dsa-rating.zip
    - name: Publish
      uses: actions/upload-artifact@v3
      with:
        name: DSA Ratings Release
        path: 'dsa-rating.zip'
